name: Release

on:
  push:
    branches:
      - develop

jobs:
  release:
    uses: RawZ06-Studio/.github/.github/workflows/node-ci-preprod.yml@main
    permissions:
      contents: write
    with:
      publishable: false       # application, pas de publish npm

  docker:
    needs: release
    uses: RawZ06-Studio/.github/.github/workflows/docker-build-push.yml@main
    permissions:
      contents: write   # Nécessaire pour les tags/releases
      packages: write   # Nécessaire pour Docker/Maven/NPM
    with:
      image_name: tracker-online-preprod
      dokploy_app_id: ioTsIwEf9kj0he8KbP6XM
    secrets: inherit
